# Broadcast

In [3]:
import numpy as np
macros = np.array([ 
[0.8, 2.9, 3.9], 
[52.4, 23.6, 36.5], 
[55.2, 31.7, 23.9], 
[14.4, 11, 4.9] 
]) 
print(macros.shape)
# Create a new array filled with zeros, 
# of the same shape as macros. 
result = np.zeros_like(macros) 

cal_per_macro = np.array([3, 3, 8]) 

# Now multiply each row of macros by 
# cal_per_macro. In Numpy, `*` is 
# element-wise multiplication between two arrays. 
for i in range(macros.shape[0]): 
	result[i, :] = macros[i, :] * cal_per_macro 

result 


(4, 3)


array([[  2.4,   8.7,  31.2],
       [157.2,  70.8, 292. ],
       [165.6,  95.1, 191.2],
       [ 43.2,  33. ,  39.2]])

In [4]:
import numpy as np 
A = np.array([[11, 22, 33], [10, 20, 30]]) 
print(A) 

b = 4
print(b) 

C = A + b 
print(C) 


[[11 22 33]
 [10 20 30]]
4
[[15 26 37]
 [14 24 34]]


# New axis usage

In [7]:
M = np.ones((3, 2))
a = np.arange(3)
M.shape, a.shape

((3, 2), (3,))

In [9]:
M + a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [10]:
a[:, np.newaxis].shape

(3, 1)

In [11]:
M + a[:, np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

# Zip functionality

In [19]:
# Python code to demonstrate the working of 
# unzip 

# initializing lists 

name = [ "Manjeet", "Nikhil", "Shambhavi", "Astha" ] 
roll_no = [ 4, 1, 3, 2 ] 
marks = [ 40, 50, 60, 70 ] 

# using zip() to map values 
mapped = zip(name, roll_no, marks)
#print(mapped)

# converting values to print as list 
mapped = list(mapped) 

# printing resultant values 
print ("The zipped result is : ",end="") 
print (mapped) 

print("\n") 

# unzipping values 
namz, roll_noz, marksz = zip(*mapped) 

print ("The unzipped result: \n",end="") 

# printing initial lists 
print ("The name list is : ",end="") 
print (namz) 

print ("The roll_no list is : ",end="") 
print (roll_noz) 

print ("The marks list is : ",end="") 
print (marksz) 


The zipped result is : [('Manjeet', 4, 40), ('Nikhil', 1, 50), ('Shambhavi', 3, 60), ('Astha', 2, 70)]


The unzipped result: 
The name list is : ('Manjeet', 'Nikhil', 'Shambhavi', 'Astha')
The roll_no list is : (4, 1, 3, 2)
The marks list is : (40, 50, 60, 70)


# try and except in Python

## try() is used in Error and Exception Handling 
### There are two kinds of errors :

### Syntax Error : Also known as Parsing Errors, most basic. Arise when the Python parser is unable to understand a line of code.
### Exception : Errors which are detected during execution. eg – ZeroDivisionError.


In [20]:
# Python code to illustrate 
# working of try() 
def divide(x, y): 
	try: 
		# Floor Division : Gives only Fractional Part as Answer 
		result = x // y 
		print("Yeah ! Your answer is :", result) 
	except ZeroDivisionError: 
		print("Sorry ! You are dividing by zero ") 

# Look at parameters and note the working of Program 
divide(3, 0) 


Sorry ! You are dividing by zero 


# Dictionary

In [24]:
Dict = {'Tim': 18,'Charlie':12,'Tiffany':22,'Robert':25}	
Boys = {'Tim': 18,'Charlie':12,'Robert':25}
Girls = {'Tiffany':22}	
studentX=Boys.copy()
studentY=Girls.copy()
print(studentX)
print(studentY)

{'Charlie': 12, 'Tim': 18, 'Robert': 25}
{'Tiffany': 22}


In [25]:
Dict = {'Tim': 18,'Charlie':12,'Tiffany':22,'Robert':25}	
Dict.update({"Sarah":9})
print(Dict)

{'Tiffany': 22, 'Charlie': 12, 'Robert': 25, 'Sarah': 9, 'Tim': 18}


In [26]:
#Dict = {'Tim': 18,'Charlie':12,'Tiffany':22,'Robert':25}	
del Dict ['Charlie']
print(Dict)

{'Tiffany': 22, 'Robert': 25, 'Sarah': 9, 'Tim': 18}


In [27]:
Dict = {'Tim': 18,'Charlie':12,'Tiffany':22,'Robert':25}	
print("Students Name: %s" % list(Dict.items()))

Students Name: [('Tiffany', 22), ('Charlie', 12), ('Robert', 25), ('Tim', 18)]


# Check if a given key already exists in a dictionary

In [28]:
Dict = {'Tim': 18,'Charlie':12,'Tiffany':22,'Robert':25}
Boys = {'Tim': 18,'Charlie':12,'Robert':25}
Girls = {'Tiffany':22}
for key in list(Dict.keys()):
    if key in list(Boys.keys()):
        print(True)
    else:       
        print(False)

False
True
True
True


# where

In [29]:
# Python program explaining 
# where() function 

import numpy as np 

# a is an array of integers. 
a = np.array([[1, 2, 3], [4, 5, 6]]) 

print(a) 

print ('Indices of elements <4') 

b = np.where(a<4) 
print(b) 

print("Elements which are <4") 
print(a[b]) 


[[1 2 3]
 [4 5 6]]
Indices of elements <4
(array([0, 0, 0]), array([0, 1, 2]))
Elements which are <4
[1 2 3]


In [33]:
import numpy as np
a = (np.random.rand(1,10)) #create a random (1,10) array
print ("a: \n" + str(a))
result = (np.where(a>0.5,1,0)) 
print ("result: \n" +str(result))

a: 
[[0.70209213 0.15268629 0.24840691 0.63196036 0.64226182 0.8304314
  0.38562548 0.4827599  0.01821125 0.84658639]]
result: 
[[1 0 0 1 1 1 0 0 0 1]]


# enumerate

In [31]:
# Python program to illustrate 
# enumerate function in loops 
l1 = ["eat","sleep","repeat"] 

# printing the tuples in object directly 
for ele in enumerate(l1): 
	print(ele) 
print
# changing index and printing separately 
for count,ele in enumerate(l1,100): 
	print(count,ele) 


(0, 'eat')
(1, 'sleep')
(2, 'repeat')
100 eat
101 sleep
102 repeat


# lambda

In [65]:
# Python code to illustrate cube of a number 
# showing difference between def() and lambda(). 
def cube(y): 
	return y*y*y; 

g = lambda x: x*x*x 
print(g(7)) 

print(cube(5)) 


343
125


# filter

In [34]:
# Python program to demonstrate working 
# of map. 

# Return double of n 
def addition(n): 
	return n + n 

# We double all numbers using map() 
numbers = (1, 2, 3, 4) 
result = map(addition, numbers) 
print(list(result)) 


[2, 4, 6, 8]


# reduce

In [67]:
# Python code to illustrate 
# reduce() with lambda() 
# to get sum of a list 
from functools import reduce
li = [5, 8, 10, 20, 50, 100] 
sum = reduce((lambda x, y: x + y), li) 
print (sum) 


193


# map

In [35]:
# Double all numbers using map and lambda 

numbers = (1, 2, 3, 4) 
result = map(lambda x: x + x, numbers) 
print(list(result)) 


[2, 4, 6, 8]


In [32]:
# Add two lists using map and lambda 

numbers1 = [1, 2, 3] 
numbers2 = [4, 5, 6] 

result = map(lambda x, y: x + y, numbers1, numbers2) 
print(list(result)) 


[5, 7, 9]


# vstack and hstack

f = np.array([1,2,3])[:,np.newaxis]
g = np.array([4,5,6])[:,np.newaxis]
print(f.shape,g.shape)
print('Horizontal Append:', np.hstack((f, g)),np.hstack((f, g)).shape)

In [46]:
print('vertically Append:', np.vstack((f, g)),np.vstack((f, g)).shape)

vertically Append: [[1]
 [2]
 [3]
 [4]
 [5]
 [6]] (6, 1)


# np.dot vs np.inner

In [49]:
>>> a=np.array([[1,2],[3,4]])
>>> b=np.array([[11,12],[13,14]])
>>> np.dot(a,b), np.inner(a,b)



(array([[37, 40],
        [85, 92]]), array([[35, 41],
        [81, 95]]))

In [52]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]


# Break statement

In [53]:
number = 0

for number in range(10):
    number = number + 1

    if number == 5:
        break    # break here

    print('Number is ' + str(number))

print('Out of loop')

Number is 1
Number is 2
Number is 3
Number is 4
Out of loop


# Continue Statement

In [54]:
number = 0

for number in range(10):
    number = number + 1

    if number == 5:
        continue    # continue here

    print('Number is ' + str(number))

print('Out of loop')

Number is 1
Number is 2
Number is 3
Number is 4
Number is 6
Number is 7
Number is 8
Number is 9
Number is 10
Out of loop


# assert Statement

In [56]:
def avg(marks):
    assert len(marks) != 0
    return sum(marks)/len(marks)

mark1 = [10]
print("Average of mark1:",avg(mark1))

Average of mark1: 10.0


# global statement

In [57]:
globvar = 10
def read1():
    print(globvar)
def write1():
    global globvar
    globvar = 5
def write2():
    globvar = 15

read1()

write1()

read1()

write2()

read1()

10
5
5


# transpose of 3D matrix

In [63]:
x_test = np.arange(30).reshape(3, 2, 5)

print(x_test)
print(x_test.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
(3, 2, 5)


In [64]:
y = np.transpose(x_test, (0, 2, 1))
print(y)
print(y.shape)

[[[ 0  5]
  [ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]]

 [[10 15]
  [11 16]
  [12 17]
  [13 18]
  [14 19]]

 [[20 25]
  [21 26]
  [22 27]
  [23 28]
  [24 29]]]
(3, 5, 2)
